apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: rangeiq
    microservice: db
  name: db
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: rangeiq
      microservice: db
  template:
    metadata:
      labels:
        app: rangeiq
        microservice: db
    spec:
      nodeSelector:
        service: database
      containers:
        - name: db
          image: rmall67/rangeiq-db:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rangeiq
    microservice: db
  name: rangeiq-db # this should match the DB_HOST in api-configmap
  namespace: default
spec:
  selector:
    app: rangeiq
    microservice: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
