version: '3.9'
services:
  client:
    image: 
    ports:
      - "8080:80"
    restart: always
    networks:
      - rangeiq-prod

  server:
    image: 
    ports:
      - "80:3000"
    restart: always
    networks:
      - rangeiq-prod

  db:
    image: 
    ports:
      - "5432:5432"
    restart: always
    networks:
      - rangeiq-prod


  networks:
    rangeiq-prod: