name: Deploy Infrastructure and Applications

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set Image name
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push MVC Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/countries-api-cld:${{ steps.vars.outputs.sha_short }}
            ${{ env.DOCKER_USERNAME}}/countries-api-cld:latest

      - name: Build and push Database Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/countries-db-cld:${{ steps.vars.outputs.sha_short }}
            ${{ env.DOCKER_USERNAME }}/countries-db-cld:latest
