name: Development test coverage

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - 'development'
  workflow_dispatch:

env:
  NODE_ENV: 'test'

jobs:
  test:
    name: Check test coverage
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: server
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        working-directory: server
        run: npm test -- --coverage --coverageReporters=json-summary
      - name: Check coverage threshold
        working-directory: server
        run: |
          COVERAGE=$(node -pe "require('./coverage/coverage-summary.json').total.statements.pct")
          echo "Total coverage: $COVERAGE%" 
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "❌ Coverage is below 60%. Found: $COVERAGE%"
            exit 1
          else
            echo "✅ Coverage check passed."
          fi
